name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Insatalling npm
        uses: actions/setup-node@v2-beta
        with:
          version: 12    

      - name: Insataling yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
          
      - name: Creating build
        run: yarn build
        
      - name: Installing surge
        run: npm install -g surge
      
      - name: Deploying on surge
        run: surge ./build myassignment-05.surge.sh --token ${{ secrets.CLASS05 }}
    
